### PR TITLE
Create a uniform formatting scheme

### PR DESCRIPTION
**Pull request by bbfh-dev**
I setup prettier configuration inside of package.json, so that code looks the same across all machines.

> [!WARNING]
> I've run `prettier . --write` as well to apply the changes, I'm not sure how easy it will be to merge with other commits. **In case** there are conflicts, the only real file that was changed manually is `package.json`. The rest can be obtained by running the same `prettier . --write` once all other commits are merged.

### CODE REVIEW

**Comment by bbfh-dev** [comment]
I think running `prettier . --write` was kind of dumb, because reading the diff its really hard to tell what was changed. So for the sake of security, @TheNuclearNexus should probably run it on his own machine and commit to main. I still stand by the `package.json` change

**Comment by TheNuclearNexus** [comment]
Yeah setting up prettier rules would be good, I'll apply them myself and just copy the settings you have here.

**Comment by bbfh-dev** [comment]
This entire branch can be deleted. The prettier config I've added is:
```json
"prettier": {
    "trailingComma": "es5",
    "tabWidth": 4,
    "useTabs": true,
    "semi": false,
    "singleQuote": false
}
```

Justification:
- `"useTabs": true` tabs are better for indentation, reasoning:
    - Single character
    - You can configure your editor to display them using as many spaces as you prefer
    - Most editors support soft tabs, so you wouldn't see a difference editing code
- `"singleQuote": false` double quotes are perfect for strings, the `'` character is used in sentences and in general it just looks better.
- The rest I just used from official prettier example, feel free to suggest any changes

**Comment by TheNuclearNexus** [comment]
Applied changes localy

**Pull request closed without merging**
